import {createContext,useCallback,useContext,useEffect,useState} from 'react';
import {DEMO_MODE} from '../services/api'; import {demoAdapter} from '../mock/adapter';
import {caseService} from '../services/caseService';import {animalService} from '../services/animalService';import {vaccinationService} from '../services/vaccinationService';import {labService} from '../services/labService';import {alertService} from '../services/alertService';import {analyticsService} from '../services/analyticsService';import {weatherService} from '../services/weatherService';import {outbreakService} from '../services/outbreakService';
import {queue,syncQueue} from '../services/offlineQueue';import {useAuth} from './AuthContext';import {readStore,writeStore} from '../utils/storage';
const Context=createContext(); const empty={cases:[],animals:[],vaccinations:[],labs:[],alerts:[],trend:[],weather:null,facilities:[]};
export function AppProvider({children}){
 const{user}=useAuth();const[data,setData]=useState(()=>DEMO_MODE?demoAdapter.load():empty);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[online,setOnline]=useState(navigator.onLine);const[syncing,setSyncing]=useState(false);const[queueCount,setQueueCount]=useState(0);const[toasts,setToasts]=useState([]);const[district,setDistrictState]=useState(()=>readStore('hw-district','Pune'));
 const toast=useCallback((message,type='success')=>{const id=crypto.randomUUID();setToasts(t=>[...t,{id,message,type}]);setTimeout(()=>setToasts(t=>t.filter(x=>x.id!==id)),6500);},[]);
 const refresh=useCallback(async()=>{if(DEMO_MODE){setData(demoAdapter.load());return;}if(!user)return;setLoading(true);setError('');try{const [cases,animals,vaccinations,labs,alerts,analytics,weather,map]=await Promise.all([caseService.list(),animalService.list(),vaccinationService.list(),['vet','field','officer'].includes(user.role)?labService.list():Promise.resolve([]),alertService.list(),analyticsService.dashboard(),weatherService.get({district}),outbreakService.map()]);setData({cases,animals,vaccinations,labs,alerts,trend:analytics.trend||[],weather,facilities:map.facilities||[],outbreaks:map.reports||[],summary:analytics.summary});}catch(e){setError(e.message);}finally{setLoading(false);}},[user,district]);
 useEffect(()=>{refresh();},[refresh]);
 const commit=useCallback(next=>{demoAdapter.save(next);setData(next);},[]);
 const submitCase=useCallback(async(payload,key=crypto.randomUUID())=>{if(!DEMO_MODE){const result=await caseService.create(payload,key);await refresh();return result;}const current=demoAdapter.load();const existing=current.cases.find(c=>c.idempotencyKey===key);if(existing)return existing;const record={...payload,id:`HW-${Date.now().toString().slice(-7)}`,idempotencyKey:key,ownerId:user.id,date:new Date().toISOString().slice(0,10),reportedTime:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),status:'Reported',labStatus:'Not requested',vet:'Unassigned',disease:payload.assessment?.disease||'Awaiting assessment',risk:payload.assessment?.risk||(['Urgent','Critical'].includes(payload.severity)?'High':payload.severity==='Moderate'?'Medium':'Low'),timeline:[{label:'Report saved in demo workspace',date:new Date().toISOString(),notes:'No report was sent to a server.'}]};commit({...current,cases:[record,...current.cases],alerts:[{id:crypto.randomUUID(),severity:record.risk==='High'?'High':'Information',category:'Case update',title:`New report ${record.id}`,location:record.village,district:record.district,date:record.date,description:'Demo case registered and awaiting veterinary review.',action:'Open case management.',read:false},...current.alerts]});return record;},[commit,refresh,user]);
 const sync=useCallback(async()=>{if(!user||!navigator.onLine)return;setSyncing(true);try{const result=await syncQueue(user.id,DEMO_MODE?'demo':'live',submitCase);if(result.synced)toast(DEMO_MODE?`${result.synced} queued report(s) saved to the local demo workspace.`:`${result.synced} report(s) submitted to the server.`);}catch(e){toast(`Report remains queued: ${e.message}`,'error');}finally{setSyncing(false);setQueueCount(queue.list().filter(i=>i.ownerId===user.id).length);}},[user,submitCase,toast]);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 useEffect(()=>{if(online&&user)sync();},[online,user,sync]);
 const saveReport=async payload=>{if(!online){const item=queue.add(payload,user.id,DEMO_MODE?'demo':'live');setQueueCount(queue.list().filter(i=>i.ownerId===user.id).length);return {id:item.id,queued:true};}return submitCase(payload);};
 const mutate=async(kind,action,payload,id)=>{if(!DEMO_MODE){const services={cases:caseService,animals:animalService,vaccinations:vaccinationService,labs:labService,alerts:alertService};const result=await services[kind][action](...(action==='update'?[id,payload]:[payload]));await refresh();return result;}const current=demoAdapter.load();const record=action==='update'?{...current[kind].find(x=>x.id===id),...payload}:{id:`${kind.slice(0,3).toUpperCase()}-${Date.now().toString().slice(-7)}`,...payload};commit({...current,[kind]:action==='update'?current[kind].map(x=>x.id===id?record:x):[record,...current[kind]]});return record;};
 const districtData={...data,cases:data.cases.filter(c=>(district==='All districts'||c.district===district)&&(user?.role!=='farmer'||c.ownerId===user.id)),animals:data.animals.filter(a=>(district==='All districts'||a.district===district)&&(user?.role!=='farmer'||a.ownerId===user.id)),alerts:data.alerts.filter(a=>district==='All districts'||a.district===district)};
 districtData.vaccinations=data.vaccinations.filter(v=>districtData.animals.some(a=>a.id===v.animalId));
 return <Context.Provider value={{data:districtData,rawData:data,loading,error,refresh,online,syncing,queueCount,sync,saveReport,mutate,toast,toasts,district,setDistrict:v=>{setDistrictState(v);writeStore('hw-district',v);},demo:DEMO_MODE,resetDemo:()=>setData(demoAdapter.reset())}}>{children}</Context.Provider>;
}
export const useApp=()=>useContext(Context);
