import {api} from './api';
export const roleToApi={farmer:'FARMER',field:'FIELD_WORKER',vet:'VETERINARIAN',officer:'DISTRICT_OFFICER'};
export const title=value=>String(value||'').toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export const statusToApi=value=>String(value).toUpperCase().replaceAll(' ','_');
export const userFromApi=u=>({...u,name:u.full_name,role:{FARMER:'farmer',FIELD_WORKER:'field',VETERINARIAN:'vet',DISTRICT_OFFICER:'officer',ADMIN:'officer'}[u.role],backendRole:u.role});
export const caseFromApi=c=>({...c,reference:c.case_reference,date:c.created_at?.slice(0,10),farmer:'Owner record protected',ownerId:c.owner_id,animalId:c.animal_id,herdId:c.herd_id,symptoms:c.observed_symptoms,disease:c.suspected_disease||'Awaiting assessment',risk:title(c.risk_level),status:title(c.status),vet:c.assigned_veterinarian_id||'Unassigned',labStatus:'See referrals',affected:c.affected_count,deaths:c.death_count,lat:c.latitude,lng:c.longitude,timeline:(c.timeline||[]).map(x=>({label:title(x.action),date:x.created_at,notes:x.details?.notes||x.details?.status||''})),notes:c.notes});
export const animalFromApi=a=>({...a,tag:a.animal_tag,age:a.approximate_age,owner:a.owner_id,ownerId:a.owner_id,status:a.health_status,vaccination:'See records',lastCheckup:'See history',records:a.records||[]});
export const vaccineFromApi=v=>({...v,animalId:v.animal_id,herdId:v.herd_id,vaccine:v.vaccine_name,lastDose:v.administered_on,nextDue:v.next_due_on,status:!v.next_due_on?'Vaccinated':v.next_due_on<new Date().toISOString().slice(0,10)?'Overdue':'Vaccinated'});
export const labLabels={REQUESTED:'Pending Samples',COLLECTED:'Collected',IN_TRANSIT:'Samples in Transit',RECEIVED:'Received',TESTING:'Testing',RESULT_AVAILABLE:'Results Available',CLOSED:'Closed'};
export const labFromApi=l=>({...l,reference:l.sample_reference,caseId:l.case_id,animalId:l.animal_id,disease:l.suspected_disease||'Awaiting assessment',sampleType:l.sample_type,collectionDate:l.collection_date,laboratory:l.laboratory_name,status:labLabels[l.status]||title(l.status)});
export const alertFromApi=a=>({...a,category:title(a.type),severity:a.severity==='INFO'?'Information':title(a.severity),description:a.message,location:[a.village,a.district].filter(Boolean).join(' · '),date:a.created_at?.slice(0,10),read:a.is_read,action:'Review the related records.'});
export async function listAll(path,mapper=x=>x,params={}){let items=[],page=1;while(true){const result=(await api.get(path,{params:{...params,page,page_size:100}})).data;items.push(...result.items.map(mapper));if(page>=result.pages||page>=100)break;page++;}return items;}
export const caseToApi=v=>({animal_id:v.herdId?null:v.animalId||null,herd_id:v.herdId||null,species:v.species,state:v.state,district:v.district,block:v.block||'',village:v.village,latitude:v.lat===''||v.lat==null?null:Number(v.lat),longitude:v.lng===''||v.lng==null?null:Number(v.lng),symptom_started_on:v.symptomStart,affected_count:Number(v.affected),death_count:Number(v.deaths),observed_symptoms:v.symptoms||'',severity:statusToApi(v.severity||'Routine'),notes:v.notes||''});
