import {useEffect,useRef} from 'react';import {Link} from 'react-router-dom';import {AlertCircle,ArrowUpRight,Check,ChevronRight,Inbox,LoaderCircle,Search,X} from 'lucide-react';
export const Button=({children,variant='',className='',loading=false,...props})=><button className={`btn ${variant} ${className}`} disabled={loading||props.disabled} {...props}>{loading&&<LoaderCircle size={16} className="spin"/>}{children}</button>;
export const Badge=({children})=><span className={`badge ${['High','Critical','Urgent','Overdue'].includes(children)?'danger':['Medium','Moderate','Under Review','Due Soon','Lab Pending','Testing','Needs review'].includes(children)?'warning':['Low','Healthy','Resolved','Closed','Vaccinated','Online'].includes(children)?'success':'neutral'}`}><span/>{children}</span>;
export const PageHeader=({eyebrow='HERDWATCH WORKSPACE',title,description,action})=><div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<div className="header-actions">{action}</div>}</div>;
export const Card=({title,subtitle,action,children,className=''})=><section className={`card ${className}`}>{title&&<div className="card-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}{children}</section>;
export const StatCard=({label,value,icon:Icon,note,tone='',to})=><Link className={`stat-card ${tone}`} to={to||'/analytics'}><div className="stat-top"><span>{label}</span><span className="stat-icon"><Icon size={18}/></span></div><div className="stat-value">{value}</div><div className="stat-note">{note}<ArrowUpRight size={14}/></div></Link>;
export const Field=({label,error,children,hint,required})=>{const id=children?.props?.id;return <div className="field"><label htmlFor={id}>{label}{required&&<span className="required"> *</span>}</label>{children}{hint&&<small>{hint}</small>}{error&&<small id={`${id}-error`} className="field-error" role="alert">{error.message||error}</small>}</div>;};
export const SearchInput=({value,onChange,placeholder='Search records…'})=><div className="search-input"><Search size={17}/><input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>;
export const EmptyState=({title='No records found',description='Try another search or change your filters.',action})=><div className="empty"><Inbox size={34}/><h3>{title}</h3><p>{description}</p>{action}</div>;
export const ErrorState=({message,onRetry})=><div className="notice danger" role="alert"><AlertCircle size={20}/><div><strong>Unable to load this workspace</strong><p>{message}</p>{onRetry&&<Button variant="secondary" onClick={onRetry}>Try again</Button>}</div></div>;
export const LoadingSkeleton=()=> <div className="skeleton-grid" aria-label="Loading workspace" role="status">{Array.from({length:6},(_,i)=><div className="skeleton" key={i}/>)}</div>;
export const Notice=({children,tone=''})=><div className={`notice ${tone}`}><AlertCircle size={18}/><div>{children}</div></div>;
export function DataTable({columns,rows,onRow,emptyTitle}){return rows.length?<div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c.key} scope="col">{c.label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}>{columns.map((c,i)=><td key={c.key}>{i===0&&onRow?<button className="table-link" onClick={()=>onRow(row)}>{c.render?c.render(row):row[c.key]}</button>:c.render?c.render(row):row[c.key]??'—'}</td>)}</tr>)}</tbody></table></div>:<EmptyState title={emptyTitle}/>;}
export function Modal({title,onClose,children}){const ref=useRef();useEffect(()=>{const previous=document.activeElement;const el=ref.current;el.focus();const handler=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=el.querySelectorAll('button:not([disabled]),input,select,textarea,a[href],[tabindex="0"]');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=old;previous?.focus();};},[onClose]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-label={title} ref={ref} tabIndex={-1}><div className="card-head"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</section></div>;}
export const Timeline=({items})=><ol className="timeline">{items.map((item,i)=><li key={i}><span className="timeline-dot"><Check size={12}/></span><div><strong>{item.label||item.type}</strong><small>{new Date(item.date).toLocaleDateString()}</small><p>{item.notes}</p></div></li>)}</ol>;
export const TextLink=({to,children})=><Link className="text-link" to={to}>{children}<ChevronRight size={15}/></Link>;
