import {Link,useNavigate} from 'react-router-dom';import {Activity,ArrowUpRight,CalendarDays,ChevronRight,ClipboardList,FlaskConical,MapPin,Plus,ShieldCheck,Stethoscope,Syringe} from 'lucide-react';import {useApp} from '../context/AppContext';import {useAuth} from '../context/AuthContext';import {useLanguage} from '../context/LanguageContext';import {Badge,Card,DataTable,PageHeader,StatCard,TextLink} from '../components/common/UI';import {TrendChart,DistributionChart,countBy} from '../components/charts/Charts';import SurveillanceMap from '../components/maps/SurveillanceMap';
export default function Dashboard(){const{data,demo,district}=useApp();const{user}=useAuth();const{t}=useLanguage();const navigate=useNavigate();const active=data.cases.filter(c=>!['Resolved','Closed'].includes(c.status));const high=data.cases.filter(c=>c.risk==='High');const vaccinated=data.vaccinations.filter(v=>v.status==='Vaccinated').length;const coverage=data.animals.length?Math.round(vaccinated/data.animals.length*100):0;const stats=[['activeCases',active.length,ClipboardList,'Awaiting or receiving care','cases'],['outbreaks',demo?'—':data.summary?.suspectedOutbreaks??'—',Activity,'Requires verified cluster data','outbreak-map'],['highRisk',new Set(high.map(c=>c.village)).size,MapPin,'Prioritise veterinary review','outbreak-map'],['monitored',data.animals.length,Stethoscope,'Registered in this workspace','animals'],['vaccinated',vaccinated,Syringe,`${coverage}% of registered animals`,'vaccination'],['pendingLabs',data.labs.filter(l=>l.status!=='Results Available').length,FlaskConical,'Samples awaiting results','laboratory']];
return <><PageHeader eyebrow={`${demo?'DEMO SURVEILLANCE':'SURVEILLANCE'} / ${district.toUpperCase()}`} title={user.role==='farmer'?'Your herd health overview':t('overview')} description={t('welcome')} action={<><span className="date-chip"><CalendarDays size={15}/>{new Date().toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</span>{user.role!=='officer'&&<Link className="btn" to="/report-case"><Plus size={17}/>{t('report')}</Link>}</>}/>
<div className="overview-banner"><div className="banner-symbol"><ShieldCheck size={27}/></div><div><strong>Every report brings us closer to healthier herds.</strong><p>{high.length} high-risk {high.length===1?'report needs':'reports need'} attention in {district}. Review early, respond together.</p></div><Link to="/cases?risk=High">Review priority cases <ArrowUpRight size={17}/></Link></div>
<div className="stats-grid">{stats.map(([label,value,icon,note,to])=><StatCard key={label} label={t(label)} value={value} icon={icon} note={note} to={user.role==='farmer'&&to==='laboratory'?'/cases':`/${to}`}/>)}</div>
<div className="dashboard-grid"><Card title={t('diseaseTrend')} subtitle={demo?'Synthetic historical series · 15–29 September':'Reported cases over time'} action={<span className="chart-key"><i/>Reported cases</span>}><TrendChart data={data.trend}/><div className="chart-foot"><span className="status-dot"/> {demo?'Historical demo series; current reports shown below.':'Reported surveillance data.'}</div></Card><Card title={t('diseaseDistribution')} subtitle="Suspected conditions · current reports"><DistributionChart data={countBy(data.cases,'disease')} donut/></Card></div>
<div className="dashboard-grid map-row"><Card title="Geographic risk overview" subtitle={`${district} · ${demo?'fictional demo sites':'reported locations'}`} action={<TextLink to="/outbreak-map">Explore map</TextLink>}><SurveillanceMap compact reports={data.cases}/></Card><Card title="Needs your attention" subtitle="Priorities across your workspace" action={<span className="count-pill">{data.alerts.filter(a=>!a.read).length} new</span>}><div className="attention-list">{data.alerts.slice(0,3).map(a=><Link key={a.id} to="/alerts"><div className={`attention-icon ${a.severity==='High'?'amber':''}`}>{a.category==='Vaccination Due'?<Syringe size={18}/>:<Activity size={18}/>}</div><div><strong>{a.title}</strong><p>{a.location}</p><small>{a.category} · {a.date}</small></div><ChevronRight size={16}/></Link>)}</div><div className="card-footer"><TextLink to="/alerts">View all notifications</TextLink></div></Card></div>
<Card title={t('recentReports')} subtitle="From the field, into coordinated care" action={<TextLink to="/cases">View all cases</TextLink>}><DataTable rows={data.cases.slice(0,5)} onRow={r=>navigate(`/cases/${r.id}`)} columns={[{key:'id',label:'Case ID'},{key:'village',label:'Village'},{key:'species',label:'Species'},{key:'symptoms',label:'Reported symptoms'},{key:'disease',label:'Suspected condition'},{key:'risk',label:'Risk',render:r=><Badge>{r.risk}</Badge>},{key:'status',label:'Status',render:r=><Badge>{r.status}</Badge>},{key:'date',label:'Reported'}]}/></Card>
<div className="dashboard-grid lower-charts"><Card title={t('riskDistribution')} subtitle="Risk indications requiring veterinary context"><DistributionChart data={countBy(data.cases,'risk')} donut/></Card><Card title={t('speciesDistribution')} subtitle="Animals in the current report register"><DistributionChart data={countBy(data.cases,'species')}/></Card></div></>;
}
